-- جدول فئات العمليات
CREATE TABLE sys_process_cat (
    cat_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cat_name       VARCHAR2(100) NOT NULL,
    screen_alias   VARCHAR2(50) NOT NULL UNIQUE,
    description    VARCHAR2(500),
    is_active      CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
    created_date   DATE DEFAULT SYSDATE NOT NULL,
    created_by     VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE sys_process_cat IS 'فئات عمليات سير العمل';
COMMENT ON COLUMN sys_process_cat.screen_alias IS 'اسم الشاشة المرتبطة في APEX';

-- جدول مراحل العملية
CREATE TABLE sys_process_stage (
    stage_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cat_id         NUMBER NOT NULL REFERENCES sys_process_cat(cat_id),
    stage_order    NUMBER(3) NOT NULL CHECK (stage_order > 0),
    stage_name     VARCHAR2(100) NOT NULL,
    approver_type  VARCHAR2(20) DEFAULT 'QUERY' CHECK (approver_type IN ('GROUP','ROLE','QUERY')),
    approver_ref   VARCHAR2(500), -- اسم المجموعة/الدور/استعلام SQL
    auto_approve   VARCHAR2(100), -- شرط الموافقة التلقائية
    created_date   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT unique_stage_order UNIQUE (cat_id, stage_order)
);

-- جدول مجموعات الموافقة
CREATE TABLE sys_approve_group (
    group_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    group_name     VARCHAR2(100) NOT NULL UNIQUE,
    description    VARCHAR2(500),
    created_date   DATE DEFAULT SYSDATE NOT NULL
);

-- جدول أعضاء المجموعات
CREATE TABLE sys_group_members (
    member_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    group_id       NUMBER NOT NULL REFERENCES sys_approve_group(group_id),
    user_id        VARCHAR2(50) NOT NULL,
    start_date     DATE DEFAULT SYSDATE NOT NULL,
    end_date       DATE
);

-- جدول بيانات سير العمل
CREATE TABLE sys_workflow_data (
    workflow_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cat_id         NUMBER NOT NULL REFERENCES sys_process_cat(cat_id),
    reference_id   VARCHAR2(100) NOT NULL, -- ID من الشاشة الأصلية
    current_stage  NUMBER NOT NULL REFERENCES sys_process_stage(stage_id),
    status         VARCHAR2(20) DEFAULT 'PENDING' 
                   CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
    initiator_id   VARCHAR2(50) NOT NULL,
    created_date   DATE DEFAULT SYSDATE NOT NULL,
    last_update    DATE DEFAULT SYSDATE NOT NULL,
    screen_data    CLOB, -- تخزين بيانات الشاشة كـ JSON
    CONSTRAINT unique_reference UNIQUE (cat_id, reference_id)
);

-- جدول سجل الموافقات
CREATE TABLE sys_workflow_history (
    history_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    workflow_id    NUMBER NOT NULL REFERENCES sys_workflow_data(workflow_id),
    stage_id       NUMBER NOT NULL REFERENCES sys_process_stage(stage_id),
    action_type    VARCHAR2(20) NOT NULL 
                   CHECK (action_type IN ('SUBMIT','APPROVE','REJECT','RETURN','DELEGATE')),
    action_by      VARCHAR2(50) NOT NULL,
    action_date    DATE DEFAULT SYSDATE NOT NULL,
    comments       VARCHAR2(1000),
    next_stage     NUMBER REFERENCES sys_process_stage(stage_id)
);

-- جدول إعدادات الإشعارات
CREATE TABLE sys_notification_settings (
    setting_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    workflow_id    NUMBER REFERENCES sys_workflow_data(workflow_id),
    stage_id       NUMBER REFERENCES sys_process_stage(stage_id),
    notify_type    VARCHAR2(20) DEFAULT 'EMAIL' CHECK (notify_type IN ('EMAIL','SMS','APP')),
    template       VARCHAR2(500) NOT NULL,
    is_active      CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N'))
);