-------------------------------------------
-- الجداول الأساسية
-------------------------------------------

-- 1. جدول تعريف العمليات (Process Definition)
CREATE TABLE SYS_PROCESS_CAT (
    PROCESS_CAT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_NAME    VARCHAR2(100) NOT NULL UNIQUE,
    STS                 NUMBER(1) DEFAULT 1 NOT NULL CHECK (STS IN (0,1)),
    DIRECT_ENTRY        NUMBER(1) DEFAULT 0 NOT NULL CHECK (DIRECT_ENTRY IN (0,1)),
    ENTER_IN_COMPLETE   NUMBER(1) DEFAULT 0 NOT NULL CHECK (ENTER_IN_COMPLETE IN (0,1)),
    APPROVE_STAGE       VARCHAR2(50),
    REJECT_STAGE        VARCHAR2(50),
    C_DATE              TIMESTAMP DEFAULT SYSTIMESTAMP,
    DESCRIPTION         VARCHAR2(500)
);

-- 2. جدول مراحل العملية (Process Stages)
CREATE TABLE SYS_PROCESS_STAGE (
    PROCESS_STAGE_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_ID      NUMBER NOT NULL,
    STAGE_NAME          VARCHAR2(100) NOT NULL,
    ORDER_NO            NUMBER NOT NULL,
    IS_DEFAULT          NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DEFAULT IN (0,1)),
    ALL_EMPLOYEE        NUMBER(1) DEFAULT 0 NOT NULL CHECK (ALL_EMPLOYEE IN (0,1)),
    FIRST_SUPERVISOR    NUMBER(1) DEFAULT 0 NOT NULL CHECK (FIRST_SUPERVISOR IN (0,1)),
    SECOND_SUPERVISOR   NUMBER(1) DEFAULT 0 NOT NULL CHECK (SECOND_SUPERVISOR IN (0,1)),
    REQUIRE_COMMENT     NUMBER(1) DEFAULT 0 NOT NULL,
    
    CONSTRAINT FK_PROCESS_CAT
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID)
        ON DELETE CASCADE
);

-- 3. جدول مجموعات المعتمدين (Approval Groups)
CREATE TABLE SYS_APPROVE_GROUP (
    APPROVE_GROUP_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_ID      NUMBER NOT NULL,
    PROCESS_STAGE_ID    NUMBER NOT NULL,
    GROUP_NAME          VARCHAR2(100) NOT NULL,
    IN_SAME_BRANCH      NUMBER(1) DEFAULT 0 NOT NULL CHECK (IN_SAME_BRANCH IN (0,1)),
    REQUIRED_APPROVALS  NUMBER DEFAULT 1 NOT NULL,
    APPROVAL_STRATEGY   VARCHAR2(20) DEFAULT 'ANY' CHECK(APPROVAL_STRATEGY IN ('ANY','ALL','MAJORITY')),
    AUTO_APPROVE_DAYS   NUMBER DEFAULT 0,
    
    CONSTRAINT FK_PROCESS_CAT_GROUP
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_PROCESS_STAGE_GROUP
        FOREIGN KEY (PROCESS_STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID)
        ON DELETE CASCADE
);

-- 4. جداول تفاصيل المعتمدين
CREATE TABLE SYS_APPROVEGROUP_POSTYPE (
    SEQ_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPROVE_GROUP_ID    NUMBER NOT NULL,
    POSITION_TYPE       NUMBER NOT NULL,
    APPROVE_TYPE        NUMBER NOT NULL CHECK (APPROVE_TYPE IN (1,2)),
    
    CONSTRAINT FK_GROUP_POSTYPE
        FOREIGN KEY (APPROVE_GROUP_ID)
        REFERENCES SYS_APPROVE_GROUP(APPROVE_GROUP_ID)
        ON DELETE CASCADE
);

CREATE TABLE SYS_APPROVEGROUP_POSNAME (
    SEQ_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPROVE_GROUP_ID    NUMBER NOT NULL,
    POSITION_NAME       VARCHAR2(100) NOT NULL,
    APPROVE_TYPE        NUMBER NOT NULL CHECK (APPROVE_TYPE IN (1,2)),
    
    CONSTRAINT FK_GROUP_POSNAME
        FOREIGN KEY (APPROVE_GROUP_ID)
        REFERENCES SYS_APPROVE_GROUP(APPROVE_GROUP_ID)
        ON DELETE CASCADE
);

CREATE TABLE SYS_APPROVEGROUP_USERS (
    SEQ_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPROVE_GROUP_ID    NUMBER NOT NULL,
    EMPLOYEE_ID         NUMBER NOT NULL,
    APPROVE_TYPE        NUMBER NOT NULL CHECK (APPROVE_TYPE IN (1,2)),
    
    CONSTRAINT FK_GROUP_USERS
        FOREIGN KEY (APPROVE_GROUP_ID)
        REFERENCES SYS_APPROVE_GROUP(APPROVE_GROUP_ID)
        ON DELETE CASCADE
);

-- 5. جدول بيانات الطلبات (Workflow Data)
CREATE TABLE SYS_WORKFLOW_DATA (
    DATA_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_ID      NUMBER NOT NULL,
    PROCESS_STAGE_ID    NUMBER NOT NULL,
    REFERENCE_GUID      VARCHAR2(50) NOT NULL UNIQUE,
    SCRN_ALIAS          VARCHAR2(100) NOT NULL,
    CURRENT_DATA        CLOB,
    ALL_COMMENTS        CLOB,
    FINAL_STATUS        VARCHAR2(20) DEFAULT 'PENDING' CHECK (FINAL_STATUS IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
    BRANCH_ID           NUMBER NOT NULL,
    CREATED_BY          NUMBER NOT NULL,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT FK_DATA_PROCESS_CAT
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID),
        
    CONSTRAINT FK_DATA_PROCESS_STAGE
        FOREIGN KEY (PROCESS_STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID)
);

-- 6. جدول سجل المراحل (Stage Log)
CREATE TABLE SYS_WORKFLOW_STAGE_LOG (
    LOG_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_ID             NUMBER NOT NULL,
    PROCESS_CAT_ID      NUMBER NOT NULL,
    PROCESS_STAGE_ID    NUMBER NOT NULL,
    APPROVER_ID         NUMBER NOT NULL,
    ACTION_TYPE         VARCHAR2(20) NOT NULL CHECK (ACTION_TYPE IN ('APPROVE','REJECT','RETURN','ESCALATE','SUBMIT')),
    ACTION_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMMENT_TEXT        VARCHAR2(1000),
    IS_CURRENT_STAGE    NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_CURRENT_STAGE IN (0,1)),
    
    CONSTRAINT FK_LOG_DATA
        FOREIGN KEY (DATA_ID)
        REFERENCES SYS_WORKFLOW_DATA(DATA_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_LOG_PROCESS_CAT
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID),
        
    CONSTRAINT FK_LOG_PROCESS_STAGE
        FOREIGN KEY (PROCESS_STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID)
);

-- 7. جدول الشروط الديناميكية (Dynamic Routing Conditions)
CREATE TABLE SYS_WORKFLOW_CONDITIONS (
    CONDITION_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_ID        NUMBER NOT NULL,
    FIELD_NAME            VARCHAR2(100) NOT NULL,
    OPERATOR              VARCHAR2(10) NOT NULL CHECK (OPERATOR IN ('=','<>','<','>','<=','>=','IN','NOT IN','LIKE')),
    VALUE_MATCH           VARCHAR2(500) NOT NULL,
    ACTION_TYPE           VARCHAR2(20) NOT NULL CHECK (ACTION_TYPE IN ('SKIP','REDIRECT','AUTO_APPROVE')),
    AFFECTED_STAGE_ID     NUMBER NOT NULL,
    REDIRECT_TO_STAGE_ID  NUMBER,
    
    CONSTRAINT FK_CONDITION_PROCESS
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_AFFECTED_STAGE
        FOREIGN KEY (AFFECTED_STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID),
        
    CONSTRAINT FK_REDIRECT_STAGE
        FOREIGN KEY (REDIRECT_TO_STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID)
);

-- 8. جدول الإشعارات (Notifications)
CREATE TABLE SYS_ALARM_NOTIFICATION (
    SEQ_ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMPLOYEE_ID          NUMBER NOT NULL,
    PROCESS_CAT_ID       NUMBER NOT NULL,
    PROCESS_STAGE_ID     NUMBER NOT NULL,
    ACTION_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
    URL                  VARCHAR2(2000),
    NOTIFICATION_HEAD    VARCHAR2(500) NOT NULL,
    NOTIFICATION_DESC    VARCHAR2(2000),
    IS_ACTIVE            NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    IS_READ              NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_READ IN (0,1)),
    ESCALATION_LEVEL     NUMBER DEFAULT 0,
    NOTIFICATION_TYPE    VARCHAR2(20) DEFAULT 'EMAIL' CHECK(NOTIFICATION_TYPE IN ('EMAIL','SMS','PUSH','SYSTEM')),
    
    CONSTRAINT FK_NOTIF_PROCESS_CAT
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID),
        
    CONSTRAINT FK_NOTIF_PROCESS_STAGE
        FOREIGN KEY (PROCESS_STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID)
);

-- 9. جدول تفويض الصلاحيات (Delegations)
CREATE TABLE SYS_DELEGATIONS (
    DELEGATION_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DELEGATOR_ID        NUMBER NOT NULL,
    DELEGATE_TO_ID      NUMBER NOT NULL,
    START_DATE          DATE NOT NULL,
    END_DATE            DATE NOT NULL,
    PROCESS_CAT_ID      NUMBER,
    IS_ACTIVE           NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    
    CONSTRAINT FK_DELEGATOR_EMP
        FOREIGN KEY (DELEGATOR_ID)
        REFERENCES HR_EMPLOYEES(EMPLOYEE_ID),
        
    CONSTRAINT FK_DELEGATE_TO_EMP
        FOREIGN KEY (DELEGATE_TO_ID)
        REFERENCES HR_EMPLOYEES(EMPLOYEE_ID),
        
    CONSTRAINT FK_DELEGATION_PROCESS
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID)
);

-- 10. جدول المرفقات (Attachments)
CREATE TABLE SYS_ATTACHMENTS (
    ATTACHMENT_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_ID             NUMBER NOT NULL,
    FILE_NAME           VARCHAR2(255) NOT NULL,
    FILE_PATH           VARCHAR2(2000) NOT NULL,
    UPLOADED_BY         NUMBER NOT NULL,
    UPLOAD_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT FK_ATTACHMENTS_DATA
        FOREIGN KEY (DATA_ID)
        REFERENCES SYS_WORKFLOW_DATA(DATA_ID)
        ON DELETE CASCADE
);

-- 11. جدول قواعد التصعيد (Escalation Rules)
CREATE TABLE SYS_ESCALATION_RULES (
    ESCALATION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_ID NUMBER NOT NULL,
    STAGE_ID NUMBER NOT NULL,
    TRIGGER_AFTER_HOURS NUMBER DEFAULT 24,
    ESCALATE_TO_GROUP_ID NUMBER NOT NULL,
    MAX_ESCALATIONS NUMBER DEFAULT 3,
    
    CONSTRAINT FK_ESCALATION_PROCESS
        FOREIGN KEY (PROCESS_CAT_ID)
        REFERENCES SYS_PROCESS_CAT(PROCESS_CAT_ID),
        
    CONSTRAINT FK_ESCALATION_STAGE
        FOREIGN KEY (STAGE_ID)
        REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE_ID),
        
    CONSTRAINT FK_ESCALATION_GROUP
        FOREIGN KEY (ESCALATE_TO_GROUP_ID)
        REFERENCES SYS_APPROVE_GROUP(APPROVE_GROUP_ID)
);

-- 12. جدول الموظفين (Employees)
CREATE TABLE HR_EMPLOYEES (
    EMPLOYEE_ID         NUMBER PRIMARY KEY,
    FULL_NAME           VARCHAR2(100) NOT NULL,
    EMAIL               VARCHAR2(100) UNIQUE,
    POSITION_TYPE       NUMBER,
    POSITION_NAME       VARCHAR2(100),
    BRANCH_ID           NUMBER,
    SUPERVISOR_ID       NUMBER,
    SECOND_SUPERVISOR_ID NUMBER,
    IS_ACTIVE           NUMBER(1) DEFAULT 1
);

-- 13. جدول الفروع (Branches)
CREATE TABLE SYS_BRANCHES (
    BRANCH_ID           NUMBER PRIMARY KEY,
    BRANCH_NAME         VARCHAR2(100) NOT NULL,
    REGION              VARCHAR2(50),
    COUNTRY             VARCHAR2(50)
);

-- 14. جدول أنواع الوظائف (Job Positions)
CREATE TABLE HR_POSITION_TYPES (
    POSITION_TYPE_ID    NUMBER PRIMARY KEY,
    POSITION_TYPE_NAME  VARCHAR2(100) NOT NULL,
    JOB_LEVEL           NUMBER
);

-------------------------------------------
-- الفهارس
-------------------------------------------
CREATE INDEX IDX_WF_DATA_CAT ON SYS_WORKFLOW_DATA(PROCESS_CAT_ID);
CREATE INDEX IDX_WF_DATA_STAGE ON SYS_WORKFLOW_DATA(PROCESS_STAGE_ID);
CREATE INDEX IDX_STAGELOG_DATA ON SYS_WORKFLOW_STAGE_LOG(DATA_ID);
CREATE INDEX IDX_APPGROUP_STAGE ON SYS_APPROVE_GROUP(PROCESS_STAGE_ID);
CREATE INDEX IDX_WF_DATA_GUID ON SYS_WORKFLOW_DATA(REFERENCE_GUID);
CREATE INDEX IDX_LOG_ACTION ON SYS_WORKFLOW_STAGE_LOG(ACTION_TYPE, ACTION_DATE);
CREATE INDEX IDX_DELEGATION_DATES ON SYS_DELEGATIONS(START_DATE, END_DATE);
CREATE INDEX IDX_NOTIF_ACTIVE ON SYS_ALARM_NOTIFICATION(IS_ACTIVE, IS_READ);