-- =====================================================
-- DDL لإنشاء جداول نظام سير العمل الديناميكي
-- =====================================================

-- 1. جدول فئات العمليات
CREATE TABLE SYS_PROCESS_CAT (
    PROCESS_CAT          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT_NAME     VARCHAR2(100) NOT NULL UNIQUE,
    APPROVE_STAGE        VARCHAR2(50),
    REJECT_STAGE         VARCHAR2(50),
    BLK_ID               VARCHAR2(250),
    REVERS_ALLOW         VARCHAR2(250),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    U_USER               VARCHAR2(50),
    U_DATE               TIMESTAMP,
    D_STS                NUMBER(1)    DEFAULT 0 CHECK (D_STS IN (0,1)),
    LVL                  VARCHAR2(50) DEFAULT '0',
    STS                  NUMBER(1)    DEFAULT 1 CHECK (STS IN (0,1)),
    GUID                 VARCHAR2(50) DEFAULT SYS_GUID(),
    ENTER_IN_COMPLETE    NUMBER(1)    DEFAULT 0,
    EDIT_ALLOW           NUMBER(1)    DEFAULT 0,
    DIRECT_ENTRY         NUMBER(1)    DEFAULT 0,
    MAX_DURATION         NUMBER       DEFAULT 7,
    SPECIAL_FLAGS        VARCHAR2(500)
);

COMMENT ON TABLE SYS_PROCESS_CAT IS 'فئات العمليات الرئيسية مع إعدادات التخصيص';

-- 2. جدول مراحل العمليات
CREATE TABLE SYS_PROCESS_STAGE (
    PROCESS_STAGE        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT          NUMBER       NOT NULL,
    PROCESS_STAGE_NAME   VARCHAR2(50) NOT NULL,
    DESCRIPTION          VARCHAR2(200),
    ALL_EMPLOYEE         NUMBER(1)    DEFAULT 0 CHECK (ALL_EMPLOYEE IN (0,1)),
    FIRST_SUPERVISOR_APPROVE  NUMBER(1) DEFAULT 0 CHECK (FIRST_SUPERVISOR_APPROVE IN (0,1)),
    SECOND_SUPERVISOR_APPROVE NUMBER(1) DEFAULT 0 CHECK (SECOND_SUPERVISOR_APPROVE IN (0,1)),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    U_USER               VARCHAR2(50),
    U_DATE               TIMESTAMP,
    D_STS                NUMBER(1)    DEFAULT 0 CHECK (D_STS IN (0,1)),
    LVL                  VARCHAR2(50) DEFAULT '0',
    STS                  NUMBER(1)    DEFAULT 1 CHECK (STS IN (0,1)),
    GUID                 VARCHAR2(50) DEFAULT SYS_GUID(),
    ORDER_NO             NUMBER       DEFAULT 0,
    IS_DEFAULT           NUMBER(1)    DEFAULT 0 CHECK (IS_DEFAULT IN (0,1)),
    MANDATORY_COMMENT    NUMBER(1)    DEFAULT 0 CHECK (MANDATORY_COMMENT IN (0,1)),
    ATTACHMENT_REQUIRED  NUMBER(1)    DEFAULT 0 CHECK (ATTACHMENT_REQUIRED IN (0,1)),
    AUTO_ADVANCE         NUMBER(1)    DEFAULT 0 CHECK (AUTO_ADVANCE IN (0,1)),
    CONSTRAINT FK_STAGE_CAT FOREIGN KEY (PROCESS_CAT) REFERENCES SYS_PROCESS_CAT(PROCESS_CAT)
);

COMMENT ON TABLE SYS_PROCESS_STAGE IS 'مراحل سير العمل مع قواعد التحقق';

-- 3. جدول مجموعات الموافقة
CREATE TABLE SYS_APPROVE_GROUP (
    APPROVE_GROUP_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_CAT          NUMBER       NOT NULL,
    PROCESS_STAGE        NUMBER       NOT NULL,
    APP_GROUP_NAME       VARCHAR2(200) NOT NULL UNIQUE,
    IN_SAME_BRANCH       NUMBER(1)    DEFAULT 0 CHECK (IN_SAME_BRANCH IN (0,1)),
    DESCRIPTION          VARCHAR2(250),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    U_USER               VARCHAR2(50),
    U_DATE               TIMESTAMP,
    D_STS                NUMBER(1)    DEFAULT 0 CHECK (D_STS IN (0,1)),
    LVL                  VARCHAR2(50) DEFAULT '0',
    STS                  NUMBER(1)    DEFAULT 1 CHECK (STS IN (0,1)),
    GUID                 VARCHAR2(50) DEFAULT SYS_GUID(),
    MIN_APPROVALS        NUMBER       DEFAULT 1,
    CONSTRAINT FK_AG_CAT   FOREIGN KEY (PROCESS_CAT)  REFERENCES SYS_PROCESS_CAT(PROCESS_CAT),
    CONSTRAINT FK_AG_STAGE FOREIGN KEY (PROCESS_STAGE) REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE)
);

COMMENT ON TABLE SYS_APPROVE_GROUP IS 'مجموعات الموافقة ضمن كل مرحلة';

-- 4. جدول بيانات سير العمل
CREATE TABLE SYS_WORKFLOW_DATA (
    DATA_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CURRENT_DATA         CLOB,
    ALL_COMMENTS         CLOB,
    PROCESS_TYPE         VARCHAR2(50),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    U_USER               VARCHAR2(50),
    U_DATE               TIMESTAMP,
    D_STS                NUMBER(1)    DEFAULT 0 CHECK (D_STS IN (0,1)),
    LVL                  VARCHAR2(50) DEFAULT '0',
    STS                  NUMBER(1)    DEFAULT 1 CHECK (STS IN (0,1)),
    GUID                 VARCHAR2(50) DEFAULT SYS_GUID(),
    PROCESS_CAT          NUMBER       NOT NULL,
    PROCESS_STAGE        NUMBER       NOT NULL,
    REFERENCE_GUID       VARCHAR2(50),
    SCRN_ALIAS           VARCHAR2(100),
    HAS_MASTER           NUMBER(1)    DEFAULT 0 CHECK (HAS_MASTER IN (0,1)),
    TBL                  VARCHAR2(100),
    PAGE_NO              NUMBER,
    BRANCH_ID            NUMBER,
    VALIDATION_STATUS    NUMBER(1)    DEFAULT 0 CHECK (VALIDATION_STATUS IN (0,1,2)),
    VALIDATION_ERRORS    CLOB,
    DUPLICATE_CHECK      NUMBER(1)    DEFAULT 0 CHECK (DUPLICATE_CHECK IN (0,1)),
    CONFLICT_CHECK       NUMBER(1)    DEFAULT 0 CHECK (CONFLICT_CHECK IN (0,1)),
    AUTO_APPROVED        NUMBER(1)    DEFAULT 0 CHECK (AUTO_APPROVED IN (0,1)),
    URGENCY_LEVEL        NUMBER(1)    DEFAULT 3 CHECK (URGENCY_LEVEL IN (1,2,3)),
    CUSTOM_ATTRIBUTES    CLOB,
    EXPIRY_DATE          DATE,
    CONSTRAINT FK_WFD_CAT   FOREIGN KEY (PROCESS_CAT)  REFERENCES SYS_PROCESS_CAT(PROCESS_CAT),
    CONSTRAINT FK_WFD_STAGE FOREIGN KEY (PROCESS_STAGE) REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE)
);

COMMENT ON TABLE SYS_WORKFLOW_DATA IS 'بيانات سير العمل مع حالة التحقق';
CREATE TABLE "SYS_APPROVEGROUP_EMP" 
   (	"SEQ_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPROVE_GROUP_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"APPROVE_TYPE" NUMBER, 
	"C_USER" VARCHAR2(50) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER), 
	"C_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"U_USER" VARCHAR2(50), 
	"U_DATE" TIMESTAMP (6), 
	"D_STS" NUMBER(1,0) DEFAULT 0, 
	"LVL" VARCHAR2(50) DEFAULT 0, 
	"STS" NUMBER(1,0) DEFAULT 1, 
	"GUID" VARCHAR2(50) DEFAULT sys_guid(), 
	"PROCESS_CAT" NUMBER, 
	"PROCESS_STAGE" NUMBER, 
	 PRIMARY KEY ("SEQ_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SYS_APPROVEGROUP_EMP_UK1" UNIQUE ("APPROVE_GROUP_ID", "EMP_ID", "APPROVE_TYPE", "D_STS")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SYS_APPROVEGROUP_EMP" ADD FOREIGN KEY ("APPROVE_GROUP_ID")
	  REFERENCES "SYS_APPROVE_GROUP" ("APPROVE_GROUP_ID") ENABLE;
  ALTER TABLE "SYS_APPROVEGROUP_EMP" ADD FOREIGN KEY ("EMP_ID")
	  REFERENCES "HR_EMPLOYEES" ("EMP_ID") ENABLE;


  CREATE TABLE "SYS_APPROVEGROUP_POSNAME" 
   (	"SEQ_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPROVE_GROUP_ID" NUMBER, 
	"POSITION_NAME" NUMBER, 
	"APPROVE_TYPE" NUMBER, 
	"C_USER" VARCHAR2(50) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER), 
	"C_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"U_USER" VARCHAR2(50), 
	"U_DATE" TIMESTAMP (6), 
	"D_STS" NUMBER(1,0) DEFAULT 0, 
	"LVL" VARCHAR2(50) DEFAULT 0, 
	"STS" NUMBER(1,0) DEFAULT 1, 
	"GUID" VARCHAR2(50) DEFAULT sys_guid(), 
	"PROCESS_CAT" NUMBER, 
	"PROCESS_STAGE" NUMBER, 
	 PRIMARY KEY ("SEQ_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SYS_APPROVEGROUP_POSNAMEGD" UNIQUE ("GUID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SYS_APPROVEGROUP_POSNAME" ADD FOREIGN KEY ("APPROVE_GROUP_ID")
	  REFERENCES "SYS_APPROVE_GROUP" ("APPROVE_GROUP_ID") ENABLE;


  CREATE TABLE "SYS_APPROVEGROUP_POSTYPE" 
   (	"SEQ_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPROVE_GROUP_ID" NUMBER, 
	"POSITION_TYPE" NUMBER, 
	"APPROVE_TYPE" NUMBER, 
	"C_USER" VARCHAR2(50) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER), 
	"C_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"U_USER" VARCHAR2(50), 
	"U_DATE" TIMESTAMP (6), 
	"D_STS" NUMBER(1,0) DEFAULT 0, 
	"LVL" VARCHAR2(50) DEFAULT 0, 
	"STS" NUMBER(1,0) DEFAULT 1, 
	"GUID" VARCHAR2(50) DEFAULT sys_guid(), 
	"PROCESS_CAT" NUMBER, 
	"PROCESS_STAGE" NUMBER, 
	 PRIMARY KEY ("SEQ_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SYS_APPROVEGROUP_POSTYPE" ADD FOREIGN KEY ("APPROVE_GROUP_ID")
	  REFERENCES "SYS_APPROVE_GROUP" ("APPROVE_GROUP_ID") ENABLE;
-- 5. جدول قواعد التحقق
CREATE TABLE SYS_VALIDATION_RULES (
    RULE_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_NAME            VARCHAR2(200) NOT NULL,
    DESCRIPTION          VARCHAR2(1000),
    RULE_TYPE            VARCHAR2(20)  NOT NULL CHECK (RULE_TYPE IN ('FIELD','RECORD','STAGE','GLOBAL')),
    TARGET_OBJECT        VARCHAR2(100),
    CONDITION_LOGIC      CLOB         NOT NULL,
    ERROR_MESSAGE        VARCHAR2(1000) NOT NULL,
    ACTIVE               NUMBER(1)    DEFAULT 1 CHECK (ACTIVE IN (0,1)),
    PRIORITY             NUMBER       DEFAULT 1,
    PROCESS_CAT          NUMBER,
    PROCESS_STAGE        NUMBER,
    SPECIAL_ACTION       VARCHAR2(50),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_VR_CAT   FOREIGN KEY (PROCESS_CAT)  REFERENCES SYS_PROCESS_CAT(PROCESS_CAT),
    CONSTRAINT FK_VR_STAGE FOREIGN KEY (PROCESS_STAGE) REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE)
);

COMMENT ON TABLE SYS_VALIDATION_RULES IS 'قواعد التحقق الديناميكية لكل مرحلة';

-- 6. جدول ربط القواعد بالمراحل
CREATE TABLE SYS_STAGE_RULES (
    STAGE_RULE_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_STAGE        NUMBER       NOT NULL,
    RULE_ID              NUMBER       NOT NULL,
    EXECUTION_ORDER      NUMBER       DEFAULT 1 NOT NULL,
    MANDATORY            NUMBER(1)    DEFAULT 1 CHECK (MANDATORY IN (0,1)),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_SR_STAGE FOREIGN KEY (PROCESS_STAGE) REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE),
    CONSTRAINT FK_SR_RULE  FOREIGN KEY (RULE_ID)        REFERENCES SYS_VALIDATION_RULES(RULE_ID)
);

COMMENT ON TABLE SYS_STAGE_RULES IS 'ربط قواعد التحقق بمراحل سير العمل';

-- 7. جدول التفويضات
CREATE TABLE SYS_DELEGATION (
    DELEGATION_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FROM_EMPLOYEE        NUMBER       NOT NULL,
    TO_EMPLOYEE          NUMBER       NOT NULL,
    PROCESS_CAT          NUMBER,
    START_DATE           TIMESTAMP    NOT NULL,
    END_DATE             TIMESTAMP    NOT NULL,
    ACTIVE               NUMBER(1)    DEFAULT 1 CHECK (ACTIVE IN (0,1)),
    REASON               VARCHAR2(1000),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DELEG_CAT FOREIGN KEY (PROCESS_CAT) REFERENCES SYS_PROCESS_CAT(PROCESS_CAT),
    CONSTRAINT CHK_NO_SELF_DELEGATION CHECK (FROM_EMPLOYEE <> TO_EMPLOYEE),
    CONSTRAINT CHK_VALID_DATES       CHECK (END_DATE > START_DATE)
);

COMMENT ON TABLE SYS_DELEGATION IS 'تفويضات الموظفين للموافقة على الطلبات';

-- 8. جدول المرفقات
CREATE TABLE SYS_ATTACHMENT (
    ATTACHMENT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WORKFLOW_DATA_ID     NUMBER       NOT NULL,
    FILE_NAME            VARCHAR2(500) NOT NULL,
    FILE_TYPE            VARCHAR2(50)  NOT NULL,
    FILE_SIZE            NUMBER,
    CONTENT              BLOB,
    STAGE_ID             NUMBER,
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ATT_WFD  FOREIGN KEY (WORKFLOW_DATA_ID) REFERENCES SYS_WORKFLOW_DATA(DATA_ID),
    CONSTRAINT FK_ATT_STAGE FOREIGN KEY (STAGE_ID)          REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE)
) LOB (CONTENT) STORE AS SECUREFILE;

COMMENT ON TABLE SYS_ATTACHMENT IS 'مرفقات سير العمل';

-- 9. جدول الإشعارات
CREATE TABLE SYS_ALARM_NOTIFICATION (
    SEQ_ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    URL                  VARCHAR2(2000),
    BLK_ID               VARCHAR2(500),
    ACTION_ID            VARCHAR2(50),
    PROCESS_CAT          NUMBER,
    PROCESS_STAGE        NUMBER,
    EMPLOYEE_ID          NUMBER       NOT NULL,
    SENDER_EMPLOYEE      NUMBER,
    ACTION_DATE          TIMESTAMP    DEFAULT SYSTIMESTAMP,
    BRANCH_ID            NUMBER,
    NOTIFICATION_HEAD    VARCHAR2(500) NOT NULL,
    NOTIFICATION_DESCRIPTION VARCHAR2(2000),
    IS_ACTIVE            NUMBER(1)    DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    READ_STATUS          NUMBER(1)    DEFAULT 0 CHECK (READ_STATUS IN (0,1)),
    EXPIRY_DATE          DATE,
    PRIORITY             NUMBER(1)    DEFAULT 3 CHECK (PRIORITY IN (1,2,3)),
    C_USER               VARCHAR2(50) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER),
    C_DATE               TIMESTAMP    DEFAULT SYSTIMESTAMP,
    U_USER               VARCHAR2(50),
    U_DATE               TIMESTAMP,
    D_STS                NUMBER(1)    DEFAULT 0 CHECK (D_STS IN (0,1)),
    LVL                  VARCHAR2(50) DEFAULT '0',
    STS                  NUMBER(1)    DEFAULT 1 CHECK (STS IN (0,1)),
    GUID                 VARCHAR2(50) DEFAULT SYS_GUID(),
    NOTIFICATION_TYPE    NUMBER,
    NOTIFICATION_LVL     NUMBER,
    CONNECTION_ID        NUMBER,
    CONSTRAINT FK_AN_CAT   FOREIGN KEY (PROCESS_CAT)  REFERENCES SYS_PROCESS_CAT(PROCESS_CAT),
    CONSTRAINT FK_AN_STAGE FOREIGN KEY (PROCESS_STAGE) REFERENCES SYS_PROCESS_STAGE(PROCESS_STAGE)
);

COMMENT ON TABLE SYS_ALARM_NOTIFICATION IS 'إشعارات نظام سير العمل';

-- 10. جدول System Audit
CREATE TABLE SYSTEM_AUDIT (
    AUDIT_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACTION               VARCHAR2(500) NOT NULL,
    ACTION_DATE          TIMESTAMP    DEFAULT SYSTIMESTAMP,
    USER_NAME            VARCHAR2(100) DEFAULT USER,
    STATUS               VARCHAR2(20) NOT NULL,
    ERROR_MESSAGE        VARCHAR2(2000),
    DURATION             NUMBER
);

-- 11. جدول System Error Log
CREATE TABLE SYSTEM_ERROR_LOG (
    ERROR_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ERROR_MESSAGE        VARCHAR2(2000) NOT NULL,
    ERROR_DATE           TIMESTAMP    DEFAULT SYSTIMESTAMP,
    SOURCE_MODULE        VARCHAR2(100),
    DATA_ID              NUMBER,
    RESOLVED             NUMBER(1)    DEFAULT 0 CHECK (RESOLVED IN (0,1))
);

-- 12. جدول Custom Settings
CREATE TABLE SYS_CUSTOM_SETTINGS (
    SETTING_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SETTING_NAME         VARCHAR2(200) NOT NULL UNIQUE,
    SETTING_VALUE        CLOB,
    DESCRIPTION          VARCHAR2(1000),
    LAST_MODIFIED        TIMESTAMP    DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SYS_CUSTOM_SETTINGS IS 'تخزين إعدادات التخصيص للنظام';

-- 13. فهارس مقترحة للأداء
CREATE INDEX IDX_WFDATA_CAT_STAGE ON SYS_WORKFLOW_DATA(PROCESS_CAT, PROCESS_STAGE);
CREATE INDEX IDX_VALID_RULES_CAT_STAGE ON SYS_VALIDATION_RULES(PROCESS_CAT, PROCESS_STAGE);
